steps:
- label: "Run benchmark - GPT-OSS-120B FP4"
  agents:
    queue: perf-h200
  plugins:
    - docker#v5.2.0:
        image: vllm/vllm-openai:v0.15.1
        entrypoint: ["/bin/bash", "-c"]
        command: ["./benchmark/run.sh"]
        always-pull: true
        propagate-environment: true
        gpus: all
        environment:
        - HF_HOME=/dev/shm/
        - HF_TOKEN
        volumes:
        - /dev/shm:/dev/shm
